version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: w3d0VEeecm4UsRu9
    depends_on:
      - db
    ports:
      - "9000:9000"

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: w3d0VEeecm4UsRu9
      MYSQL_ROOT_PASSWORD: yIk5B012YkXbd1lU
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3336:3306"

  node:
    image: node:22
    container_name: vite_node
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: >
      sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"  # Vite default
    environment:
      - HOST=0.0.0.0

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_artisan
    entrypoint: ["php", "artisan"]
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: w3d0VEeecm4UsRu9

volumes:
  db_data:

